using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace Labs.DataAccess.Web.Code.StronglyTypedDataset
{
    /// <summary>
    /// This is a demo implementation showing how to do dataaccess in .NET using strongly typed dataset(s).
    /// </summary>
    public class UserRepository : BaseRepository, IUserRepository
    {
        public User GetById(int id)
        {
            using (var usersAdapter = new StronglyTypedDatasetTableAdapters.UsersTableAdapter()
                {
                    Connection = new SqlConnection(ConnectionString)
                })
            {
                var user = new StronglyTypedDataset.UsersDataTable();
                usersAdapter.FillById(user, id);

                return Map(user.FirstOrDefault());  
            }            
        }

        /// <summary>
        /// Maps the Userrow type generated by the Strongly Typed Dataset to our own POCO type.
        /// </summary>
        /// <param name="user">User row handed to us by the Strongly Typed Dataset</param>
        /// <returns>Our own dataaccess technology independent User object.</returns>
        private Code.User Map(Labs.DataAccess.Web.Code.StronglyTypedDataset.StronglyTypedDataset.UsersRow user)
        {
            if (user == null)
                return null;

            return new Code.User()
            {
                Id = user.Id,
                Firstname = user.FirstName,
                Lastname = user.LastName,
                Email = user.Email
            };
        }
    }
}